require 'nvim-only-plugin-config.nvim-lspconfig'
require 'nvim-only-plugin-config.nvim-cmp'
require 'nvim-only-plugin-config.nvim-lsp-installer'
require 'nvim-only-plugin-config.lspkind'
require 'nvim-only-plugin-config.trouble'
require 'nvim-only-plugin-config.bufferline'
